/**
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * 
 * @author Vadim Kisen
 *
 * copyright 2010 by uTest 
 */
package com.utest.domain;

// Generated Oct 7, 2009 11:18:35 AM by Hibernate Tools 3.2.4.GA

/**
 * CountryLocale generated by hbm2java
 */
public class CountryLocale implements LocaleDescriptable
{

	private CountryLocaleId	id;
	private String			name;
	private Integer			sortOrder;

	public CountryLocale()
	{
	}

	public CountryLocale(final CountryLocaleId id, final String name)
	{
		this.id = id;
		this.name = name;
	}

	public CountryLocale(final CountryLocaleId id, final String name, final Integer sortOrder)
	{
		this.id = id;
		this.name = name;
		this.sortOrder = sortOrder;
	}

	public CountryLocaleId getId()
	{
		return this.id;
	}

	public void setId(final CountryLocaleId id)
	{
		this.id = id;
	}

	public String getName()
	{
		return this.name;
	}

	public void setName(final String name)
	{
		this.name = name;
	}

	public Integer getSortOrder()
	{
		return this.sortOrder;
	}

	public void setSortOrder(final Integer sortOrder)
	{
		this.sortOrder = sortOrder;
	}

	public Integer getEntityId()
	{
		return this.getId().getCountryId();
	}

	@Override
	public String getLocaleCode()
	{
		return getId().getLocaleCode();
	}
}
