/**
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * 
 * @author Vadim Kisen
 *
 * copyright 2010 by uTest 
 */
package com.utest.domain;

// Generated Oct 7, 2009 11:18:35 AM by Hibernate Tools 3.2.4.GA

/**
 * CountryStateLocaleId generated by hbm2java
 */
public class CountryStateLocaleId implements java.io.Serializable
{

	private Integer	countryStateId;
	private String	localeCode;

	public CountryStateLocaleId()
	{
	}

	public CountryStateLocaleId(Integer countryStateId, String localeCode)
	{
		this.countryStateId = countryStateId;
		this.localeCode = localeCode;
	}

	public Integer getCountryStateId()
	{
		return this.countryStateId;
	}

	public void setCountryStateId(Integer countryStateId)
	{
		this.countryStateId = countryStateId;
	}

	public String getLocaleCode()
	{
		return this.localeCode;
	}

	public void setLocaleCode(String localeCode)
	{
		this.localeCode = localeCode;
	}

	@Override
	public boolean equals(Object other)
	{
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CountryStateLocaleId))
			return false;
		CountryStateLocaleId castOther = (CountryStateLocaleId) other;

		return ((this.getCountryStateId() == castOther.getCountryStateId()) || (this.getCountryStateId() != null && castOther.getCountryStateId() != null && this
				.getCountryStateId().equals(castOther.getCountryStateId())))
				&& ((this.getLocaleCode() == castOther.getLocaleCode()) || (this.getLocaleCode() != null && castOther.getLocaleCode() != null && this.getLocaleCode().equals(
						castOther.getLocaleCode())));
	}

	@Override
	public int hashCode()
	{
		int result = 17;

		result = 37 * result + (getCountryStateId() == null ? 0 : this.getCountryStateId().hashCode());
		result = 37 * result + (getLocaleCode() == null ? 0 : this.getLocaleCode().hashCode());
		return result;
	}

}
