/**
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * 
 * @author Vadim Kisen
 *
 * copyright 2010 by uTest 
 */
package com.utest.domain;

// Generated Oct 7, 2009 11:18:35 AM by Hibernate Tools 3.2.4.GA

/**
 * BugTypeLocaleId generated by hbm2java
 */
public class EntityTypeLocaleId implements java.io.Serializable
{

	private Integer	entityTypeId;
	private String	localeCode;

	public EntityTypeLocaleId()
	{
	}

	public EntityTypeLocaleId(final Integer entityTypeId, final String localeCode)
	{
		this.setEntityTypeId(entityTypeId);
		this.localeCode = localeCode;
	}

	public String getLocaleCode()
	{
		return this.localeCode;
	}

	public void setLocaleCode(final String localeCode)
	{
		this.localeCode = localeCode;
	}

	public void setEntityTypeId(final Integer entityTypeId)
	{
		this.entityTypeId = entityTypeId;
	}

	public Integer getEntityTypeId()
	{
		return entityTypeId;
	}

	@Override
	public int hashCode()
	{
		final int prime = 31;
		int result = 1;
		result = prime * result + ((entityTypeId == null) ? 0 : entityTypeId.hashCode());
		result = prime * result + ((localeCode == null) ? 0 : localeCode.hashCode());
		return result;
	}

	@Override
	public boolean equals(final Object obj)
	{
		if (this == obj)
		{
			return true;
		}
		if (obj == null)
		{
			return false;
		}
		if (getClass() != obj.getClass())
		{
			return false;
		}
		final EntityTypeLocaleId other = (EntityTypeLocaleId) obj;
		if (entityTypeId == null)
		{
			if (other.entityTypeId != null)
			{
				return false;
			}
		}
		else if (!entityTypeId.equals(other.entityTypeId))
		{
			return false;
		}
		if (localeCode == null)
		{
			if (other.localeCode != null)
			{
				return false;
			}
		}
		else if (!localeCode.equals(other.localeCode))
		{
			return false;
		}
		return true;
	}

}
