/**
 *
 * Licensed under the GNU General Public License (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.gnu.org/licenses/gpl.txt
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * 
 * @author Vadim Kisen
 *
 * copyright 2010 by uTest 
 */
package com.utest.domain;

import java.util.List;

/**
 * EnvironmentProfile generated by hbm2java
 */
public class EnvironmentProfileExploded extends EnvironmentProfile
{

	private List<EnvironmentGroupExploded>	environmentGroups;
	private List<Environment>				environments;

	public EnvironmentProfileExploded()
	{
		super();
	}

	public void setEnvironmentGroups(List<EnvironmentGroupExploded> environmentGroups)
	{
		this.environmentGroups = environmentGroups;
	}

	public List<EnvironmentGroupExploded> getEnvironmentGroups()
	{
		return environmentGroups;
	}

	public void setEnvironments(List<Environment> environments)
	{
		this.environments = environments;
	}

	public List<Environment> getEnvironments()
	{
		return environments;
	}
}
