/**
 *
 * Licensed under the GNU General Public License (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.gnu.org/licenses/gpl.txt
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * 
 * @author Vadim Kisen
 *
 * copyright 2010 by uTest 
 */
package com.utest.domain;

/**
 * EnvironmentProfileEnvironment generated by hbm2java
 */
public class EnvironmentProfileEnvironment extends TimelineEntity
{

	private Integer	environmentId;
	private Integer	environmentProfileId;
	private boolean	optional	= false;
	private Integer	weightIndex	= 0;

	public EnvironmentProfileEnvironment()
	{
	}

	public Integer getEnvironmentId()
	{
		return environmentId;
	}

	public void setEnvironmentId(Integer environmentId)
	{
		this.environmentId = environmentId;
	}

	public Integer getEnvironmentProfileId()
	{
		return environmentProfileId;
	}

	public void setEnvironmentProfileId(Integer environmentProfileId)
	{
		this.environmentProfileId = environmentProfileId;
	}

	public boolean isOptional()
	{
		return optional;
	}

	public void setOptional(boolean optional)
	{
		this.optional = optional;
	}

	public Integer getWeightIndex()
	{
		return weightIndex;
	}

	public void setWeightIndex(Integer weightIndex)
	{
		this.weightIndex = weightIndex;
	}

}
