/**
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * 
 * @author Vadim Kisen
 *
 * copyright 2010 by uTest 
 */
package com.utest.domain;

// Generated Sep 3, 2010 1:57:10 PM by Hibernate Tools 3.2.4.GA

/**
 * ParentDependableEnvironment generated by hbm2java
 */
public class ParentDependableEnvironment extends TimelineEntity
{

	private Integer	environmentId;
	private Integer	parentEnvironmentId;
	private Integer	companyId;

	public ParentDependableEnvironment()
	{
	}

	public ParentDependableEnvironment(final Integer environmentId, final Integer parentEnvironmentId)
	{
		this.environmentId = environmentId;
		this.parentEnvironmentId = parentEnvironmentId;
	}

	public Integer getEnvironmentId()
	{
		return this.environmentId;
	}

	public void setEnvironmentId(final Integer environmentId)
	{
		this.environmentId = environmentId;
	}

	public Integer getParentEnvironmentId()
	{
		return this.parentEnvironmentId;
	}

	public void setParentEnvironmentId(final Integer parentEnvironmentId)
	{
		this.parentEnvironmentId = parentEnvironmentId;
	}

	@Override
	public boolean equals(final Object other)
	{
		if ((this == other))
		{
			return true;
		}
		if ((other == null))
		{
			return false;
		}
		if (!(other instanceof ParentDependableEnvironment))
		{
			return false;
		}
		final ParentDependableEnvironment castOther = (ParentDependableEnvironment) other;

		return ((this.getEnvironmentId() == castOther.getEnvironmentId()) || ((this.getEnvironmentId() != null) && (castOther.getEnvironmentId() != null) && this
				.getEnvironmentId().equals(castOther.getEnvironmentId())))
				&& ((this.getParentEnvironmentId() == castOther.getParentEnvironmentId()) || ((this.getParentEnvironmentId() != null)
						&& (castOther.getParentEnvironmentId() != null) && this.getParentEnvironmentId().equals(castOther.getParentEnvironmentId())));
	}

	@Override
	public int hashCode()
	{
		int result = 17;

		result = 37 * result + (getEnvironmentId() == null ? 0 : this.getEnvironmentId().hashCode());
		result = 37 * result + (getParentEnvironmentId() == null ? 0 : this.getParentEnvironmentId().hashCode());
		return result;
	}

	public void setCompanyId(Integer companyId)
	{
		this.companyId = companyId;
	}

	public Integer getCompanyId()
	{
		return companyId;
	}

}
