/**
 *
 * Licensed under the GNU General Public License (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.gnu.org/licenses/gpl.txt
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * 
 * @author Vadim Kisen
 *
 * copyright 2010 by uTest 
 */
package com.utest.domain;

// Generated Oct 7, 2009 11:18:35 AM by Hibernate Tools 3.2.4.GA

/**
 * UserRoleId generated by hbm2java
 */
public class RolePermission extends TimelineEntity
{

	private Integer	permissionId;
	private Integer	accessRoleId;

	public RolePermission()
	{
	}

	public RolePermission(final Integer permissionId, final Integer accessRoleId)
	{
		this.permissionId = permissionId;
		this.accessRoleId = accessRoleId;
	}

	public Integer getPermissionId()
	{
		return this.permissionId;
	}

	public void setPermissionId(final Integer permissionId)
	{
		this.permissionId = permissionId;
	}

	public Integer getAccessRoleId()
	{
		return this.accessRoleId;
	}

	public void setAccessRoleId(final Integer accessRoleId)
	{
		this.accessRoleId = accessRoleId;
	}

}
