/**
 *
 * Licensed under the GNU General Public License (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.gnu.org/licenses/gpl.txt
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * 
 * @author Vadim Kisen
 *
 * copyright 2010 by uTest 
 */
package com.utest.domain;

// Generated Sep 3, 2010 1:57:10 PM by Hibernate Tools 3.2.4.GA

/**
 * TestCaseStep generated by hbm2java
 */
public class TestCaseStep extends TimelineEntity implements Named
{

	private Integer	testCaseVersionId;
	private Integer	stepNumber;
	private String	name;
	private String	instruction;
	private String	expectedResult;
	private Integer	estimatedTimeInMin;

	public TestCaseStep()
	{
		super();
	}

	public TestCaseStep(final Integer testCaseVersionId, final Integer stepNumber, final String name, final String instruction, final String expectedResult)
	{
		super();
		this.testCaseVersionId = testCaseVersionId;
		this.stepNumber = stepNumber;
		this.name = name;
		this.instruction = instruction;
		this.expectedResult = expectedResult;
	}

	public TestCaseStep(final Integer testCaseVersionId, final Integer stepNumber, final String name, final String instruction, final String expectedResult,
			final Integer estimatedTimeInMin)
	{
		super();
		this.testCaseVersionId = testCaseVersionId;
		this.stepNumber = stepNumber;
		this.name = name;
		this.instruction = instruction;
		this.expectedResult = expectedResult;
		this.estimatedTimeInMin = estimatedTimeInMin;
	}

	public Integer getTestCaseVersionId()
	{
		return this.testCaseVersionId;
	}

	public void setTestCaseVersionId(final Integer testCaseVersionId)
	{
		this.testCaseVersionId = testCaseVersionId;
	}

	public Integer getStepNumber()
	{
		return this.stepNumber;
	}

	public void setStepNumber(final Integer stepNumber)
	{
		this.stepNumber = stepNumber;
	}

	public String getName()
	{
		return this.name;
	}

	public void setName(final String name)
	{
		this.name = name;
	}

	public String getInstruction()
	{
		return this.instruction;
	}

	public void setInstruction(final String instruction)
	{
		this.instruction = instruction;
	}

	public String getExpectedResult()
	{
		return this.expectedResult;
	}

	public void setExpectedResult(final String expectedResult)
	{
		this.expectedResult = expectedResult;
	}

	public Integer getEstimatedTimeInMin()
	{
		return this.estimatedTimeInMin;
	}

	public void setEstimatedTimeInMin(final Integer estimatedTimeInMin)
	{
		this.estimatedTimeInMin = estimatedTimeInMin;
	}

}
