/**
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * 
 * @author Vadim Kisen
 *
 * copyright 2010 by uTest 
 */
package com.utest.domain;

// Generated Sep 3, 2010 1:57:10 PM by Hibernate Tools 3.2.4.GA


/**
 * TestRunTestCaseAssignment generated by hbm2java
 */
public class TestRunTestCaseAssignment extends TimelineEntity implements ProductDependable, EnvironmentDependable
{

	private Integer	testRunTestCaseId;
	private Integer	productId;
	private Integer	testRunId;
	private Integer	testCaseId;
	private Integer	testCaseVersionId;
	private Integer	testerId;
	private Integer	environmentProfileId;

	public TestRunTestCaseAssignment()
	{
	}

	public TestRunTestCaseAssignment(final Integer testRunTestCaseId, final Integer productId, final Integer testRunId, final Integer testCaseId, final Integer testCaseVersionId,
			final Integer testerId)
	{
		super();
		this.testRunTestCaseId = testRunTestCaseId;
		this.productId = productId;
		this.testRunId = testRunId;
		this.testCaseId = testCaseId;
		this.testCaseVersionId = testCaseVersionId;
		this.testerId = testerId;
	}

	public TestRunTestCaseAssignment(final Integer testRunTestCaseId, final Integer productId, final Integer testRunId, final Integer testCaseId, final Integer testCaseVersionId,
			final Integer testerId, final Integer environmentProfileId)
	{
		super();
		this.testRunTestCaseId = testRunTestCaseId;
		this.productId = productId;
		this.testRunId = testRunId;
		this.testCaseId = testCaseId;
		this.testCaseVersionId = testCaseVersionId;
		this.testerId = testerId;
		this.environmentProfileId = environmentProfileId;
	}

	public Integer getTestRunTestCaseId()
	{
		return this.testRunTestCaseId;
	}

	public void setTestRunTestCaseId(final Integer testRunTestCaseId)
	{
		this.testRunTestCaseId = testRunTestCaseId;
	}

	public Integer getProductId()
	{
		return this.productId;
	}

	public void setProductId(final Integer productId)
	{
		this.productId = productId;
	}

	public Integer getTestRunId()
	{
		return this.testRunId;
	}

	public void setTestRunId(final Integer testRunId)
	{
		this.testRunId = testRunId;
	}

	public Integer getTestCaseId()
	{
		return this.testCaseId;
	}

	public void setTestCaseId(final Integer testCaseId)
	{
		this.testCaseId = testCaseId;
	}

	public Integer getTestCaseVersionId()
	{
		return this.testCaseVersionId;
	}

	public void setTestCaseVersionId(final Integer testCaseVersionId)
	{
		this.testCaseVersionId = testCaseVersionId;
	}

	public Integer getTesterId()
	{
		return this.testerId;
	}

	public void setTesterId(final Integer testerId)
	{
		this.testerId = testerId;
	}

	public Integer getEnvironmentProfileId()
	{
		return this.environmentProfileId;
	}

	public void setEnvironmentProfileId(final Integer environmentProfileId)
	{
		this.environmentProfileId = environmentProfileId;
	}

}
