/**
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * 
 * @author Vadim Kisen
 *
 * copyright 2010 by uTest 
 */
package com.utest.domain;

/**
 * TestCaseStatusLocaleId generated by hbm2java
 */

public class TestCaseStatusLocaleId implements java.io.Serializable
{

	private Integer	testCaseStatusId;
	private String	localeCode;

	public TestCaseStatusLocaleId()
	{
	}

	public TestCaseStatusLocaleId(Integer testCaseStatusId, String localeCode)
	{
		this.testCaseStatusId = testCaseStatusId;
		this.localeCode = localeCode;
	}

	public Integer getTestCaseStatusId()
	{
		return this.testCaseStatusId;
	}

	public void setTestCaseStatusId(Integer testCaseStatusId)
	{
		this.testCaseStatusId = testCaseStatusId;
	}

	public String getLocaleCode()
	{
		return this.localeCode;
	}

	public void setLocaleCode(String localeCode)
	{
		this.localeCode = localeCode;
	}

	@Override
	public boolean equals(Object other)
	{
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TestCaseStatusLocaleId))
			return false;
		TestCaseStatusLocaleId castOther = (TestCaseStatusLocaleId) other;

		return ((this.getTestCaseStatusId() == castOther.getTestCaseStatusId()) || (this.getTestCaseStatusId() != null && castOther.getTestCaseStatusId() != null && this
				.getTestCaseStatusId().equals(castOther.getTestCaseStatusId())))
				&& ((this.getLocaleCode() == castOther.getLocaleCode()) || (this.getLocaleCode() != null && castOther.getLocaleCode() != null && this.getLocaleCode().equals(
						castOther.getLocaleCode())));
	}

	@Override
	public int hashCode()
	{
		int result = 17;

		result = 37 * result + (getTestCaseStatusId() == null ? 0 : this.getTestCaseStatusId().hashCode());
		result = 37 * result + (getLocaleCode() == null ? 0 : this.getLocaleCode().hashCode());
		return result;
	}

}
