/**
 *
 * Licensed under the GNU General Public License (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.gnu.org/licenses/gpl.txt
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * 
 * @author Vadim Kisen
 *
 * copyright 2010 by uTest 
 */
package com.utest.domain;

/**
 * TestPlanStatusLocaleId generated by hbm2java
 */

public class TestPlanStatusLocaleId implements java.io.Serializable
{

	private Integer	testPlanStatusId;
	private String	localeCode;

	public TestPlanStatusLocaleId()
	{
	}

	public TestPlanStatusLocaleId(Integer testPlanStatusId, String localeCode)
	{
		this.testPlanStatusId = testPlanStatusId;
		this.localeCode = localeCode;
	}

	public Integer getTestPlanStatusId()
	{
		return this.testPlanStatusId;
	}

	public void setTestPlanStatusId(Integer testPlanStatusId)
	{
		this.testPlanStatusId = testPlanStatusId;
	}

	public String getLocaleCode()
	{
		return this.localeCode;
	}

	public void setLocaleCode(String localeCode)
	{
		this.localeCode = localeCode;
	}

	@Override
	public boolean equals(Object other)
	{
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TestPlanStatusLocaleId))
			return false;
		TestPlanStatusLocaleId castOther = (TestPlanStatusLocaleId) other;

		return ((this.getTestPlanStatusId() == castOther.getTestPlanStatusId()) || (this.getTestPlanStatusId() != null && castOther.getTestPlanStatusId() != null && this
				.getTestPlanStatusId().equals(castOther.getTestPlanStatusId())))
				&& ((this.getLocaleCode() == castOther.getLocaleCode()) || (this.getLocaleCode() != null && castOther.getLocaleCode() != null && this.getLocaleCode().equals(
						castOther.getLocaleCode())));
	}

	@Override
	public int hashCode()
	{
		int result = 17;

		result = 37 * result + (getTestPlanStatusId() == null ? 0 : this.getTestPlanStatusId().hashCode());
		result = 37 * result + (getLocaleCode() == null ? 0 : this.getLocaleCode().hashCode());
		return result;
	}

}
