/**
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * 
 * @author Vadim Kisen
 *
 * copyright 2010 by uTest 
 */
package com.utest.domain;

import java.util.List;

// Generated Sep 3, 2010 1:57:10 PM by Hibernate Tools 3.2.4.GA

/**
 * TestCase generated by hbm2java
 */
public class TestCase extends Entity implements ProductDependable
{

	private Integer					productId;
	private Integer					maxAttachmentSizeInMbytes;
	private Integer					maxNumberOfAttachments;
	private Integer					testCycleId;
	private TestCaseVersion			latestVersion;
	private List<ProductComponent>	productComponents;

	public TestCase()
	{
	}

	public TestCase(final Integer productId, final Integer maxAttachmentSizeInMbytes, final Integer maxNumberOfAttachments)
	{
		this.productId = productId;
		this.maxAttachmentSizeInMbytes = maxAttachmentSizeInMbytes;
		this.maxNumberOfAttachments = maxNumberOfAttachments;
	}

	public TestCase(final Integer productId, final Integer maxAttachmentSizeInMbytes, final Integer maxNumberOfAttachments, final Integer testCycleId)
	{
		this.productId = productId;
		this.maxAttachmentSizeInMbytes = maxAttachmentSizeInMbytes;
		this.maxNumberOfAttachments = maxNumberOfAttachments;
		this.testCycleId = testCycleId;
	}

	public Integer getProductId()
	{
		return this.productId;
	}

	public void setProductId(final Integer productId)
	{
		this.productId = productId;
	}

	public Integer getMaxAttachmentSizeInMbytes()
	{
		return this.maxAttachmentSizeInMbytes;
	}

	public void setMaxAttachmentSizeInMbytes(final Integer maxAttachmentSizeInMbytes)
	{
		this.maxAttachmentSizeInMbytes = maxAttachmentSizeInMbytes;
	}

	public Integer getMaxNumberOfAttachments()
	{
		return this.maxNumberOfAttachments;
	}

	public void setMaxNumberOfAttachments(final Integer maxNumberOfAttachments)
	{
		this.maxNumberOfAttachments = maxNumberOfAttachments;
	}

	public Integer getTestCycleId()
	{
		return this.testCycleId;
	}

	public void setTestCycleId(final Integer testCycleId)
	{
		this.testCycleId = testCycleId;
	}

	public void setLatestVersion(final TestCaseVersion latestVersion)
	{
		this.latestVersion = latestVersion;
	}

	public TestCaseVersion getLatestVersion()
	{
		return latestVersion;
	}

	public void setProductComponents(final List<ProductComponent> productComponents)
	{
		this.productComponents = productComponents;
	}

	public List<ProductComponent> getProductComponents()
	{
		return productComponents;
	}

}
