/**
 *
 * Licensed under the GNU General Public License (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.gnu.org/licenses/gpl.txt
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * 
 * @author Vadim Kisen
 *
 * copyright 2010 by uTest 
 */
package com.utest.domain;

// Generated Sep 3, 2010 1:57:10 PM by Hibernate Tools 3.2.4.GA

/**
 * TestRunTestCase generated by hbm2java
 */
public class TestRunTestCase extends TimelineEntity implements EnvironmentDependable, TestCaseContainerDependable
{

	private Integer			testRunId;
	private Integer			testCycleId;
	private Integer			productId;
	private Integer			companyId;
	private TestCaseVersion	testCaseVersion;
	private Integer			testCaseVersionId;
	private Integer			testCaseId;
	private Integer			priorityId;
	private Integer			runOrder;
	private boolean			blocking;
	private boolean			selfAssignAllowed;
	private Integer			selfAssignLimit;
	private boolean			selfAssignPerEnvironment;
	private Integer			environmentProfileId;
	private Integer			testSuiteId;

	public TestRunTestCase()
	{
	}

	public TestRunTestCase(final Integer testRunId, final Integer testCaseVersionId, final Integer testCaseId, final Integer priorityId, final Integer runOrder,
			final boolean blocking, final boolean selfAssignAllowed, final Integer selfAssignLimit, final boolean selfAssignPerEnvironment)
	{
		super();
		this.testRunId = testRunId;
		this.testCaseVersionId = testCaseVersionId;
		this.testCaseId = testCaseId;
		this.priorityId = priorityId;
		this.runOrder = runOrder;
		this.blocking = blocking;
		this.selfAssignAllowed = selfAssignAllowed;
		this.selfAssignLimit = selfAssignLimit;
		this.selfAssignPerEnvironment = selfAssignPerEnvironment;
	}

	public TestRunTestCase(final Integer testRunId, final Integer testCaseVersionId, final Integer testCaseId, final Integer priorityId, final Integer runOrder,
			final boolean blocking, final boolean selfAssignAllowed, final Integer selfAssignLimit, final boolean selfAssignPerEnvironment, final Integer environmentProfileId,
			final Integer testSuiteId)
	{
		super();
		this.testRunId = testRunId;
		this.testCaseVersionId = testCaseVersionId;
		this.testCaseId = testCaseId;
		this.priorityId = priorityId;
		this.runOrder = runOrder;
		this.blocking = blocking;
		this.selfAssignAllowed = selfAssignAllowed;
		this.selfAssignLimit = selfAssignLimit;
		this.selfAssignPerEnvironment = selfAssignPerEnvironment;
		this.environmentProfileId = environmentProfileId;
		this.testSuiteId = testSuiteId;
	}

	public Integer getTestRunId()
	{
		return this.testRunId;
	}

	public void setTestRunId(final Integer testRunId)
	{
		this.testRunId = testRunId;
	}

	public Integer getTestCaseVersionId()
	{
		return this.testCaseVersionId;
	}

	public void setTestCaseVersionId(final Integer testCaseVersionId)
	{
		this.testCaseVersionId = testCaseVersionId;
	}

	public Integer getTestCaseId()
	{
		return this.testCaseId;
	}

	public void setTestCaseId(final Integer testCaseId)
	{
		this.testCaseId = testCaseId;
	}

	public Integer getPriorityId()
	{
		return this.priorityId;
	}

	public void setPriorityId(final Integer priorityId)
	{
		this.priorityId = priorityId;
	}

	public Integer getRunOrder()
	{
		return this.runOrder;
	}

	public void setRunOrder(final Integer runOrder)
	{
		this.runOrder = runOrder;
	}

	public boolean isBlocking()
	{
		return this.blocking;
	}

	public void setBlocking(final boolean blocking)
	{
		this.blocking = blocking;
	}

	public boolean isSelfAssignAllowed()
	{
		return this.selfAssignAllowed;
	}

	public void setSelfAssignAllowed(final boolean selfAssignAllowed)
	{
		this.selfAssignAllowed = selfAssignAllowed;
	}

	public Integer getSelfAssignLimit()
	{
		return this.selfAssignLimit;
	}

	public void setSelfAssignLimit(final Integer selfAssignLimit)
	{
		this.selfAssignLimit = selfAssignLimit;
	}

	public Integer getTestCycleId()
	{
		return testCycleId;
	}

	public void setTestCycleId(Integer testCycleId)
	{
		this.testCycleId = testCycleId;
	}

	public Integer getProductId()
	{
		return productId;
	}

	public void setProductId(Integer productId)
	{
		this.productId = productId;
	}

	public Integer getCompanyId()
	{
		return companyId;
	}

	public void setCompanyId(Integer companyId)
	{
		this.companyId = companyId;
	}

	public boolean isSelfAssignPerEnvironment()
	{
		return this.selfAssignPerEnvironment;
	}

	public void setSelfAssignPerEnvironment(final boolean selfAssignPerEnvironment)
	{
		this.selfAssignPerEnvironment = selfAssignPerEnvironment;
	}

	public Integer getEnvironmentProfileId()
	{
		return this.environmentProfileId;
	}

	public void setEnvironmentProfileId(final Integer environmentProfileId)
	{
		this.environmentProfileId = environmentProfileId;
	}

	public Integer getTestSuiteId()
	{
		return this.testSuiteId;
	}

	public void setTestSuiteId(final Integer testSuiteId)
	{
		this.testSuiteId = testSuiteId;
	}

	public TestCaseVersion getTestCaseVersion()
	{
		return testCaseVersion;
	}

	@Override
	public Integer getTestCaseContainerId()
	{
		return testRunId;
	}

	@Override
	public void setTestCaseContainerId(Integer containerId)
	{
		testRunId = containerId;
	}

	public void setTestCaseVersion(TestCaseVersion testCaseVersion)
	{
		this.testCaseVersion = testCaseVersion;
	}
}
