/**
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * 
 * @author Vadim Kisen
 *
 * copyright 2010 by uTest 
 */
package com.utest.domain;

// Generated Sep 3, 2010 1:57:10 PM by Hibernate Tools 3.2.4.GA

/**
 * TestCaseTag generated by hbm2java
 */
public class TestCaseTag extends TimelineEntity
{

	private Integer	testCaseVersionId;
	private Integer	tagId;

	public TestCaseTag()
	{
	}

	public TestCaseTag(final Integer testCaseVersionId, final Integer tagId)
	{
		super();
		this.testCaseVersionId = testCaseVersionId;
		this.setTagId(tagId);
	}

	public Integer getTestCaseVersionId()
	{
		return this.testCaseVersionId;
	}

	public void setTestCaseVersionId(final Integer testCaseVersionId)
	{
		this.testCaseVersionId = testCaseVersionId;
	}

	public void setTagId(Integer tagId)
	{
		this.tagId = tagId;
	}

	public Integer getTagId()
	{
		return tagId;
	}
}
