/**
 *
 * Licensed under the GNU General Public License (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.gnu.org/licenses/gpl.txt
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * 
 * @author Vadim Kisen
 *
 * copyright 2010 by uTest 
 */
package com.utest.domain;

// Generated Sep 3, 2010 1:57:10 PM by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * Product generated by hbm2java
 */
public class TimelineEntity extends Entity implements TimelineVersionable
{

	private Integer	createdBy;
	private Date	createDate;
	private Integer	lastChangedBy;
	private Date	lastChangeDate;
	private Integer	version;

	public TimelineEntity()
	{
	}

	public TimelineEntity(final Integer createdBy, final Date createDate, final Integer lastChangedBy, final Date lastChangeDate)
	{
		this.createdBy = createdBy;
		this.createDate = createDate;
		this.lastChangedBy = lastChangedBy;
		this.lastChangeDate = lastChangeDate;
	}

	public Integer getCreatedBy()
	{
		return this.createdBy;
	}

	public void setCreatedBy(final Integer createdBy)
	{
		this.createdBy = createdBy;
	}

	public Date getCreateDate()
	{
		return this.createDate;
	}

	public void setCreateDate(final Date createDate)
	{
		this.createDate = createDate;
	}

	public Integer getLastChangedBy()
	{
		return this.lastChangedBy;
	}

	public void setLastChangedBy(final Integer lastChangedBy)
	{
		this.lastChangedBy = lastChangedBy;
	}

	public Date getLastChangeDate()
	{
		return this.lastChangeDate;
	}

	public void setLastChangeDate(final Date lastChangeDate)
	{
		this.lastChangeDate = lastChangeDate;
	}

	public void setVersion(final Integer version)
	{
		this.version = version;
	}

	public Integer getVersion()
	{
		return version;
	}

	@Override
	public boolean isNew()
	{
		return (getCreateDate() == null);
	}
}
