/**
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * 
 * @author Vadim Kisen
 *
 * copyright 2010 by uTest 
 */
package com.utest.domain;

// Generated Oct 7, 2009 11:18:35 AM by Hibernate Tools 3.2.4.GA

/**
 * UserStatus generated by hbm2java
 */
public class UserStatus extends LocalizedEntity
{

	public static final Integer	USER_STATUS_ACTIVE		= new Integer(1);
	public static final Integer	USER_STATUS_INACTIVE	= new Integer(2);
	public static final Integer	USER_STATUS_DISABLED	= new Integer(3);
	public static final Integer	USER_STATUS_WATCH_LIST	= new Integer(4);

	public UserStatus()
	{
	}

}
