/**
 *
 * Licensed under the GNU General Public License (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.gnu.org/licenses/gpl.txt
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * 
 * @author Vadim Kisen
 *
 * copyright 2010 by uTest 
 */
package com.utest.domain;

// Generated Oct 7, 2009 11:18:35 AM by Hibernate Tools 3.2.4.GA

/**
 * UserStatusLocaleId generated by hbm2java
 */
public class UserStatusLocaleId implements java.io.Serializable
{

	private Integer	userStatusId;
	private String	localeCode;

	public UserStatusLocaleId()
	{
	}

	public UserStatusLocaleId(Integer userStatusId, String localeCode)
	{
		this.userStatusId = userStatusId;
		this.localeCode = localeCode;
	}

	public Integer getUserStatusId()
	{
		return this.userStatusId;
	}

	public void setUserStatusId(Integer userStatusId)
	{
		this.userStatusId = userStatusId;
	}

	public String getLocaleCode()
	{
		return this.localeCode;
	}

	public void setLocaleCode(String localeCode)
	{
		this.localeCode = localeCode;
	}

	@Override
	public boolean equals(Object other)
	{
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserStatusLocaleId))
			return false;
		UserStatusLocaleId castOther = (UserStatusLocaleId) other;

		return ((this.getUserStatusId() == castOther.getUserStatusId()) || (this.getUserStatusId() != null && castOther.getUserStatusId() != null && this.getUserStatusId().equals(
				castOther.getUserStatusId())))
				&& ((this.getLocaleCode() == castOther.getLocaleCode()) || (this.getLocaleCode() != null && castOther.getLocaleCode() != null && this.getLocaleCode().equals(
						castOther.getLocaleCode())));
	}

	@Override
	public int hashCode()
	{
		int result = 17;

		result = 37 * result + (getUserStatusId() == null ? 0 : this.getUserStatusId().hashCode());
		result = 37 * result + (getLocaleCode() == null ? 0 : this.getLocaleCode().hashCode());
		return result;
	}

}
