/**
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * 
 * @author Vadim Kisen
 *
 * copyright 2010 by uTest 
 */
package com.utest.domain;

// Generated Oct 7, 2009 11:18:35 AM by Hibernate Tools 3.2.4.GA

/**
 * UserRoleId generated by hbm2java
 */
public class UserRoleId implements java.io.Serializable
{

	private Integer	userId;
	private Integer	accessRoleId;

	public UserRoleId()
	{
	}

	public UserRoleId(Integer userId, Integer accessRoleId)
	{
		this.userId = userId;
		this.accessRoleId = accessRoleId;
	}

	public Integer getUserId()
	{
		return this.userId;
	}

	public void setUserId(Integer userId)
	{
		this.userId = userId;
	}

	public Integer getAccessRoleId()
	{
		return this.accessRoleId;
	}

	public void setAccessRoleId(Integer accessRoleId)
	{
		this.accessRoleId = accessRoleId;
	}

	@Override
	public boolean equals(Object other)
	{
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserRoleId))
			return false;
		UserRoleId castOther = (UserRoleId) other;

		return ((this.getUserId() == castOther.getUserId()) || (this.getUserId() != null && castOther.getUserId() != null && this.getUserId().equals(castOther.getUserId())))
				&& ((this.getAccessRoleId() == castOther.getAccessRoleId()) || (this.getAccessRoleId() != null && castOther.getAccessRoleId() != null && this.getAccessRoleId()
						.equals(castOther.getAccessRoleId())));
	}

	@Override
	public int hashCode()
	{
		int result = 17;

		result = 37 * result + (getUserId() == null ? 0 : this.getUserId().hashCode());
		result = 37 * result + (getAccessRoleId() == null ? 0 : this.getAccessRoleId().hashCode());
		return result;
	}

}
